#!/usr/bin/env bash
# Render Casks/bohurupee.rb in Homebrew 7 stanza order from a GoReleaser checksums file.
set -euo pipefail

usage() {
  echo "usage: $0 --version VERSION --checksums PATH [--output PATH]" >&2
  exit 2
}

version=""
checksums=""
output="dist/homebrew/Casks/bohurupee.rb"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --version)
      version="${2:-}"
      shift 2
      ;;
    --checksums)
      checksums="${2:-}"
      shift 2
      ;;
    --output)
      output="${2:-}"
      shift 2
      ;;
    *)
      usage
      ;;
  esac
done

[[ -n "${version}" && -n "${checksums}" ]] || usage
[[ -f "${checksums}" ]] || {
  echo "checksums file not found: ${checksums}" >&2
  exit 1
}

version="${version#v}"

sha256_for() {
  local artifact="$1"
  local hash
  hash="$(awk -v f="${artifact}" '$2 == f { print $1; found=1 } END { exit !found }' "${checksums}")" || {
    echo "missing checksum for ${artifact} in ${checksums}" >&2
    exit 1
  }
  printf '%s' "${hash}"
}

darwin_arm64="$(sha256_for "bohurupee_${version}_darwin_arm64.tar.gz")"
darwin_amd64="$(sha256_for "bohurupee_${version}_darwin_amd64.tar.gz")"
linux_arm64="$(sha256_for "bohurupee_${version}_linux_arm64.tar.gz")"
linux_amd64="$(sha256_for "bohurupee_${version}_linux_amd64.tar.gz")"

install -d "$(dirname "${output}")"

cat >"${output}" <<EOF
# This file was generated by scripts/render-homebrew-cask.sh. DO NOT EDIT.
cask "bohurupee" do
  arch arm: "arm64", intel: "amd64"
  os macos: "darwin", linux: "linux"

  version "${version}"
  sha256 arm:          "${darwin_arm64}",
         intel:        "${darwin_amd64}",
         arm64_linux:  "${linux_arm64}",
         x86_64_linux: "${linux_amd64}"

  url "https://github.com/milon/bohurupee/releases/download/v#{version}/bohurupee_#{version}_#{os}_#{arch}.tar.gz"
  name "Bohurupee"
  desc "Local fake identity provider for OAuth and OIDC development. DEV ONLY"
  homepage "https://github.com/milon/bohurupee"

  livecheck do
    url :url
    strategy :github_latest
  end

  binary "bohurupee"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/bohurupee"]
    end
  end

  caveats <<~EOS
    Bohurupee is a local fake identity provider. DEV ONLY. It listens on 127.0.0.1:4190.
  EOS
end
EOF
